version: "3"

silent: true

tasks:
  default:
    cmds:
      - task --list

  setup:
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json
    cmds:
      - npm ci

  run:
    desc: "Run the frontend application"
    cmds:
      - npm run dev

  test:
    desc: "Run frontend tests with terminal reporter"
    cmds:
      - |
        printf "\n\033[1;97;45m TS \033[0m \033[1;35mFrontend Suite\033[0m\n\n"
        npm run test -- --coverage --coverage.reporter="text"
