version: "3"

silent: true

tasks:
  default:
    cmds:
      - task --list

  setup:
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/pyvenv.cfg
    cmds:
      - uv sync

  test:
    desc: "Run ML tests and show coverage table in terminal"
    cmds:
      - |
        printf "\n\033[1;97;42m PY \033[0m \033[1;32mML Suite\033[0m\n\n"
        uv run pytest --cov=src --cov-report=term --color=yes
